name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event.action != 'closed' && github.event.pull_request.merged == false) # Adjusted condition for PRs
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # --- START: Added steps for Tailwind CSS build ---
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Tailwind CSS (Globally for CI)
        run: npm install -g tailwindcss

      - name: Build Tailwind CSS
        working-directory: ./frontend # Execute commands within the frontend directory
        run: npx tailwindcss -i ./styles.css -o ./dist/styles.css --minify
      # --- END: Added steps for Tailwind CSS build ---

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BAY_013E2E81E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./frontend" # App source code path
          api_location: "./backend/ContactFunction" # Api source code path - optional
          output_location: "dist" # <<< IMPORTANT: Changed this to 'dist'
          # We're building Tailwind into frontend/dist, so SWA needs to know to look there
          # (relative to app_location)
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_BAY_013E2E81E }}
          action: "close"